### ISSUE TITLE
Memory Limitations on Building

### ISSUE THREAD

**Issue by GanbaruTobi** [Tokelon/tokTales-demos#1]
The file tokTales-demos/tokTales-helloworld/gradle.properties includes memory limitations for jvm. I cannot build with them.
Commenting out line 9 fixed the issue:
# org.gradle.jvmargs=-Xmx1536m

**Comment by Tokelon** [comment]
The **gradle.properties** file was auto-generated by Android Studio and as far as I know, the value for `org.gradle.jvmargs` is supposed to enable faster builds by increasing the maximum heap size for the Gradle daemon. I am unsure as to why it would cause issues, unless the system is running out of memory.

Try lowering it to something like `-Xmx1024m` or even `-Xmx512m` and see if that fixes it. You can always override the project level settings with your user specific settings in `~/.gradle/gradle.properties`.
